### ISSUE TITLE
ça fuit ?

### ISSUE THREAD

**Issue by Fil** [Aldarone/aldarone.fr#5]
![capture d ecran 2015-10-16 14 05 58](https://cloud.githubusercontent.com/assets/7001/10541159/1e874a0a-740f-11e5-867d-0eaab49bf4de.png)

vu sur https://github.com/Aldarone/aldarone.fr/network

**Comment by Aldarone** [comment]
Qu'est-ce que tu veux dire par là ?

**Comment by Fil** [comment]
le nom

**Comment by Aldarone** [comment]
Haha oui effectivement. C'est ça de commiter avec le PC du bureau.

Bon c'est pas une grosse fuite, mon pseudonymat a toujours été très light.
