### ISSUE TITLE
Typos Brotli

### ISSUE THREAD

**Issue by cladmi** [Aldarone/aldarone.fr#6]
La flemme de faire une PR dans le train :D

Au niveau des dates, il y a dans l'ordre 22 septembre, 05 octobre, 06 septembre et 10 septembre.
Je me dis qu'il y a un problème soit au début soit à la fin.

Il y a un "illes" dans la dernière traduction.

Et sinon, pour être chiant, il n'y a pas d'espaces insécables avant tes ':' du coup j'en ai un qui va à la ligne tout seul sans le mot d'avant.

J'arrive sur le blog via sebsauvage, je lis pleins d'articles dont "vous pouvez faire des issues sur github" je le fais :)

**Comment by cladmi** [comment]
Hmm vu que j'ai vu "ille" dans un autre article, je pens que le "illes" était en fait pour mettre ils/elles. My bad.

**Comment by Aldarone** [comment]
Merci ^_^ Je viens de corriger ça dans f2bcc6a28252f68615561142dae67d149da76c83
